Incorrect

Promise.reject('error');
~~~~~~~~~~~~~~~~~~~~~~~ Expected the Promise rejection reason to be an Error.

const err = new Error();
Promise.reject('an ' + err);
~~~~~~~~~~~~~~~~~~~~~~~~~~~ Expected the Promise rejection reason to be an Error.

new Promise((resolve, reject) => reject('error'));
                                 ~~~~~~~~~~~~~~~ Expected the Promise rejection reason to be an Error.

new Promise((resolve, reject) => {
  const err = new Error();
  reject('an ' + err);
  ~~~~~~~~~~~~~~~~~~~ Expected the Promise rejection reason to be an Error.
});
